# SPDX-FileCopyrightText: 2022 Katharina Fey <kookie@spacekookie.de>
#
# SPDX-License-Identifier: AGPL-3.0-or-later WITH LicenseRef-AppStore

[package]
name = "task-notify"
version = "0.1.0"
edition = "2018"
description = "Notify async tasks when someone mutates data they're interested in."
license = "AGPL-3.0-or-later"
